//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDownloaderAll.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDownloaderAll.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1} with {2} entries.
        /// </summary>
        internal static string albumTaskComplete {
            get {
                return ResourceManager.GetString("albumTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing url: {0}.
        /// </summary>
        internal static string ClosingUrl {
            get {
                return ResourceManager.GetString("ClosingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection iteration is complete.
        /// </summary>
        internal static string collectioniterationComplete {
            get {
                return ResourceManager.GetString("collectioniterationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: .
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        internal static string DispPercentage {
            get {
                return ResourceManager.GetString("DispPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading url complete.
        /// </summary>
        internal static string donereadingUrl {
            get {
                return ResourceManager.GetString("donereadingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        internal static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete from {0}.
        /// </summary>
        internal static string downloadComplete1 {
            get {
                return ResourceManager.GetString("downloadComplete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete from {0} -&gt; {1}.
        /// </summary>
        internal static string downloadComplete2 {
            get {
                return ResourceManager.GetString("downloadComplete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloadming Music Listing.
        /// </summary>
        internal static string downloadming {
            get {
                return ResourceManager.GetString("downloadming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of is duplicated.
        /// </summary>
        internal static string duplicateValue {
            get {
                return ResourceManager.GetString("duplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning, Press Enter key to continue.
        /// </summary>
        internal static string enterToContinue {
            get {
                return ResourceManager.GetString("enterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception for: {0}.
        /// </summary>
        internal static string exceptionFor {
            get {
                return ResourceManager.GetString("exceptionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download files from text file.
        /// </summary>
        internal static string fromFileDownload {
            get {
                return ResourceManager.GetString("fromFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geet Mala Music Listing.
        /// </summary>
        internal static string geetMala {
            get {
                return ResourceManager.GetString("geetMala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracenote.
        /// </summary>
        internal static string graceNote {
            get {
                return ResourceManager.GetString("graceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the folder path.
        /// </summary>
        internal static string inputFolderPath {
            get {
                return ResourceManager.GetString("inputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the url(s)...
        /// </summary>
        internal static string inputUrl {
            get {
                return ResourceManager.GetString("inputUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a long process, please do not press any key.
        /// </summary>
        internal static string longProcess {
            get {
                return ResourceManager.GetString("longProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Bogie Music Listing.
        /// </summary>
        internal static string lyricsBogie {
            get {
                return ResourceManager.GetString("lyricsBogie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported parsable auto config is provided.
        /// </summary>
        internal static string NoAutoConfigData {
            get {
                return ResourceManager.GetString("NoAutoConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Album: {0}.
        /// </summary>
        internal static string openingAlbumNameParam {
            get {
                return ResourceManager.GetString("openingAlbumNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening File: {0}.
        /// </summary>
        internal static string openingFile {
            get {
                return ResourceManager.GetString("openingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening File: {0} with {1} items.
        /// </summary>
        internal static string openingFileWithItems {
            get {
                return ResourceManager.GetString("openingFileWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening url: {0}.
        /// </summary>
        internal static string openingUrl {
            get {
                return ResourceManager.GetString("openingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Picasa]
        ///description=.
        /// </summary>
        internal static string PicasaDescription {
            get {
                return ResourceManager.GetString("PicasaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rbth Photo.
        /// </summary>
        internal static string rbthPhoto {
            get {
                return ResourceManager.GetString("rbthPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading url.
        /// </summary>
        internal static string readingUrl {
            get {
                return ResourceManager.GetString("readingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading url {0} of {1} with .
        /// </summary>
        internal static string readingUrlFrom {
            get {
                return ResourceManager.GetString("readingUrlFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading url {0} of {1} with {2} items at .
        /// </summary>
        internal static string readingUrlFromwithItemsAt {
            get {
                return ResourceManager.GetString("readingUrlFromwithItemsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT In Vision.
        /// </summary>
        internal static string rtvision {
            get {
                return ResourceManager.GetString("rtvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your option from.
        /// </summary>
        internal static string selectOptions {
            get {
                return ResourceManager.GetString("selectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sputnik Photo.
        /// </summary>
        internal static string sputnikPhoto {
            get {
                return ResourceManager.GetString("sputnikPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your choice.
        /// </summary>
        internal static string userChoice {
            get {
                return ResourceManager.GetString("userChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items .
        /// </summary>
        internal static string withItems {
            get {
                return ResourceManager.GetString("withItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items at .
        /// </summary>
        internal static string withItemsAt {
            get {
                return ResourceManager.GetString("withItemsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string working {
            get {
                return ResourceManager.GetString("working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working, Please Wait........
        /// </summary>
        internal static string workingWait {
            get {
                return ResourceManager.GetString("workingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working, Please Wait, please do not press any key........
        /// </summary>
        internal static string workingWaitKey {
            get {
                return ResourceManager.GetString("workingWaitKey", resourceCulture);
            }
        }
    }
}
